#!/bin/bash
# Compiles the display shaders. glslc comes from `brew install shaderc`.
# The results are committed (parallel-rdp/spirv*.hpp), so building VibeN64 does not need it.
cd "$(dirname "$0")" || exit 1

glslc -O crt-aperture.frag -o crt_frag.spv --target-env=vulkan1.1 -mfmt=c
glslc -O main.frag -o main_frag.spv --target-env=vulkan1.1 -mfmt=c
glslc -O main.vert -o main_vert.spv --target-env=vulkan1.1 -mfmt=c

# Every other fragment shader goes into one header, as <name>_fragment_spirv
out=../../parallel-rdp/spirv_shaders.hpp
{
	echo '#pragma once'
	echo
	echo '// Generated by data/shader/output.sh from the .frag files next to it. Do not edit.'
	for name in sharp-bilinear scanlines lcd-grid crt-geom; do
		printf '\nstatic const uint32_t %s_fragment_spirv[] =\n\t' "${name//-/_}"
		glslc -O "$name.frag" -o - --target-env=vulkan1.1 -mfmt=c || exit 1
		echo ';'
	done
} > "$out.tmp" && mv "$out.tmp" "$out"
